### ISSUE TITLE
Tool for WC4 to PCD

### ISSUE THREAD

**Issue by Cowboyjunkie** [projectpokemon/EventsGallery#265]
Hi guys!

Is there a tool to reconvert the wc4 back to the original PCD?
I need the PCD files for a Network Distro.

Regards,
John

**Comment by kamronbatman** [comment]
Probably can use PKHex. You can drag/drop them into a gen 4 save then export it.
A tool can be made from it too.

**Comment by DeadSkullzJr** [comment]
> Hi guys!
> 
> Is there a tool to reconvert the wc4 back to the original PCD? I need the PCD files for a Network Distro.
> 
> Regards, John

Based on my understanding and research, all they did was change the PCD extension to WC4. Just rename it back to PCD.

**Comment by kamronbatman** [comment]
The pokemon data itself was decrypted. Similar to EK4 to PK4.

**Comment by kamronbatman** [comment]
> > > Hi guys!
> > > Is there a tool to reconvert the wc4 back to the original PCD? I need the PCD files for a Network Distro.
> > > Regards, John
> > 
> > 
> > Based on my understanding and research, all they did was change the PCD extension to WC4. Just rename it back to PCD.
> 
> Sadly it's not that easy. I would need to re-encrypt them. I now downloaded them all by hand from Project pokemon again. But I still think from the conservation standpoint it would be better to preserve them as original as possible. So decrypting them is not a good idea.
> 
> Regards, John

I used to agree with you, but we also have PK3/PK4 files that are decrypted. We should be consistent.
Also decrypting them allowed me to check for fakes by checking battle stats and other more unknown parts of the PCD generation.

With that said, I'll build a tool for you as soon as I get time. Meanwhile, let me know if the PCD's zip file is missing anything.

**Comment by DeadSkullzJr** [comment]
I did some examinations, you guys are misunderstanding some things here.

1. You are correct about the data being decrypted, HOWEVER, this applies to PGT data NOT PCD data. This "issue" only applies to wonder card data extracted from save files via save editors such as PKHeX, of course this can be fixed by simply creating an option to export encrypted or export decrypted. The actual integrity of the PGT data isn't damage, it just needs to be encrypted again.

2. Your understanding of the extension scheme is off here. The maintainers of the event gallery quite literally changed the extension names to say WC4 to emphasize having the full wonder card data for generation four titles. Calling the entire wonder card "PCD" is misleading because wonder card data for generation four is two pieces that make a whole, PGT data and PCD data. Not all wonder cards have PCD data, some only have PGT data, WC4 only applies to wonder cards that have both PGT and PCD data. You have no need to convert WC4 to PCD when the data represented has always been the original "PCD" variants to begin with, the PGT data is just decrypted, all you need to do is encrypt the PGT data and if you really want to, just rename the WC4 extension to PCD (even though again that's misleading).

**Comment by kamronbatman** [comment]
Yeah, I am the one that created the WC4 format. :)
I have a few motivations for those:

1. We never properly preserve encrypted PKM files. So the concept of preserving original files is already off the table.
2. I needed a way to spot fakes easily without building a tool to visualize the data.
3. I wanted to combine PGT and PCD into a unified file format.
4. The format must be able to be reversed into a PGT/PCD.
5. PGT is part of a PCD, so the data was duplicative.

**Comment by DeadSkullzJr** [comment]
> Yeah, I am the one that created the WC4 format. :) I have a few motivations for those:
> 
> 1. We never properly preserve encrypted PKM files. So the concept of preserving original files is already off the table.
> 2. I needed a way to spot fakes easily without building a tool to visualize the data.
> 3. I wanted to combine PGT and PCD into a unified file format.
> 4. The format must be able to be reversed into a PGT/PCD.
> 5. PGT is part of a PCD, so the data was duplicative.
> 
> As for the full wondercard (the one on the distribute carts), I don't have those ROMs anymore, and lots of them were faked. I'll be willing to store the full wondercard data as injected by the wondercard creation program if people have that. That would be using the extension ".wc4full"

Way ahead of you:
https://projectpokemon.org/home/forums/topic/61171-deadskullzjrs-wonder-card-extraction-project/#comment-275746

**Comment by kamronbatman** [comment]
@DeadSkullzJr Do you mind making it open source?

**Comment by FlonneEx** [comment]
seconding a request for a WC4->PCD tool of some sort! we're currently working on a tool to mess with the g4 Deoxys distro to seed arbitrary pcd's, and it can't function with wc4's. it'd be nice to be able to tell people they can pluck a wc4 from the event database and use it with our tool, instead of having to hunt for the pcd.

**Comment by AdmiralKirky** [comment]
@FlonneEx : Maybe we should talk? I Have a working Distro on a portable Raspberry Pi, that can distro Wondercards/Mystery Gifts from Gen4,5,6,7 (even handmade wondercards) Does not need internet connection and has a user interface to select the WC/MG.

**Comment by kamronbatman** [comment]
For reference here is the original way I did it:
https://gist.github.com/kamronbatman/610e0e6cf9b171c9d8c44dc75a022523

**Comment by kamronbatman** [comment]
I created a converter. Requires .NET 6, and released binaries for Windows, OSX, and Linux.

https://github.com/projectpokemon/PCDWC4Converter/releases/tag/v1.0

**Comment by AdmiralKirky** [comment]
@kamronbatman Woah!!!! That is really helpful! Thank you very much!!!!
Regards,
John

P.S.: Now I have to import all the WonderCards again (because your filenames and sorting are so much better than the downloads :-))

**Comment by kamronbatman** [comment]
There was an error reported with the converter tool. I'll address it ASAP.o
