### ISSUE TITLE
UK VC Mew in wrong folder + 2 suggestions

### ISSUE THREAD

**Issue by Bl4ckSh4rk** [projectpokemon/EventsGallery#38]
I've just found the UK VC Mew is in the JPN Makuhari folder as well. I guess it was put there by mistake and should be removed.
https://github.com/projectpokemon/EventsGallery/blob/master/Released/Gen%201/JPN/Makuhari/RBY%20-%20VC%20Mew%20(UK).pk1

Also I have two suggestions:
- You are using consistent naming for wondercards which I think is nice. So I would suggest doing this for pkx files as well, currently they are all named differently.
- I would also suggest adding the special QR codes for Magearna and Partner Cap Pika as they unlock event Pokemon and there are already some QR codes in the Extras folder.
[Special QR Codes.zip](https://github.com/projectpokemon/EventsGallery/files/1572252/Special.QR.Codes.zip)

Thanks in advance.

**Comment by kamronbatman** [comment]
Thanks @Bl4ckSh4rk! I have been wanting to add the QR codes but didn't get around to it.  Thanks for uploading it.  I have also gone through and removed the extra mew.

As for the naming, you are right.  For gen 1/3/4, there are just too many for me to name them appropriately. I also haven't had time to write a PKHex.Core based program to do it for me. If you can/want to, I would appreciate a PR.

**Comment by Bl4ckSh4rk** [comment]
I can try. Is there any specific format you want them to be named in?
I guess the naming should be similar to the VC Mew "RBY - VC Mew (UK).pk1" and if there are multiple Pokemon of the same event it should be like Aura Mew "RSEFL - Aura Mew (0E20).pk3"?
If so then where exactly does the hex number in the Aura Mew file names come from?

**Comment by kamronbatman** [comment]
Yes, exactly.  As for the hex number, that is the originating seed.  Most gen 3 events have a 16bit seed.  The format is the following:
`<WCID> GameFlags - OTName <(TID)> <Shiny> <Form> <SpecialMove> <HA> [Species in English] (Lang) <(Region)> <(Seed)>`
The <> indicates that it is displayed conditionally. TID is used only to differentiate in specific circumstances where you otherwise cannot.

GameFlags are the following - RBGY, GSC, RSEFrLg, DPPtHGSS, BWB2W2, XYORAS, SMUSUM

Folders do not have a convention.  If you think of one, let me know.  I generally use the OTName or the event name.  In the case of PokePark, I nested.

PKHex does a great job of getting the seed for most events.  Exception is Negai Boshi Jirachi and 5th anniv eggs (which is 16bit seed, lookup-H, lookup-L, pid-H, pid-L, IV1, IV2). I suggest creating a program to do it since there are 500+ files.

**Comment by kamronbatman** [comment]
@Bl4ckSh4rk - Is this complete and ready to close?

**Comment by Bl4ckSh4rk** [comment]
I actually didn't even know about the special moves. But you are right, it's probably better to remove the 5th Anniv part and shorten the names.

I thought about the other wondercards as well but that would definitely take a lot more time, especially the game flags, which I probably won't have the next weeks/months.
